[[tasks]]
protocol = "MiclowStdIO"
task_name = "apply"
view_stdout = true
view_stderr = true

[tasks.command]
command = "uv"
args = ["run", "apply.py"]
working_directory = "${MICLOW_CONFIG_DIR}"
environment = { PYTHONUNBUFFERED = "1" }

[tasks.lifecycle]
desired_instances = 1

[[tasks]]
protocol = "MiclowStdIO"
task_name = "pop"
view_stdout = true
view_stderr = true

[tasks.command]
command = "uv"
args = ["run", "pop.py"]
working_directory = "${MICLOW_CONFIG_DIR}"
environment = { PYTHONUNBUFFERED = "1" }

[tasks.lifecycle]
desired_instances = 1