[[tasks]]
task_name = "main"
protocol = "MiclowStdIO"
command = "uv"
args = ["run", "python3", "main.py"]
working_directory = "${MICLOW_CONFIG_DIR}"
environment_vars = { PYTHONUNBUFFERED = "1" }
view_stdout = true
view_stderr = true

[[tasks]]
task_name = "function"
protocol = "MiclowStdIO"
command = "uv"
args = ["run", "python3", "function.py"]
working_directory = "${MICLOW_CONFIG_DIR}"
environment_vars = { PYTHONUNBUFFERED = "1" }
allow_duplicate = true
auto_start = false
view_stdout = true
view_stderr = true

[[tasks.function]]
topic = "function"