[[tasks]]
task_name = "status"
protocol = "MiclowStdIO"
command = "uv"
args = ["run", "python3", "status.py"]
working_directory = "${MICLOW_CONFIG_DIR}"
environment_vars = { PYTHONUNBUFFERED = "1" }
view_stdout = true
view_stderr = true