[[tasks]]
protocol = "MiclowStdIO"
task_name = "publisher"
command = "uv"
args = ["run", "publisher.py"]
working_directory = "${MICLOW_CONFIG_DIR}"
view_stdout = true
view_stderr = true

[[tasks.lifecycle]]
desired_instances = 1

[[tasks]]
protocol = "MiclowStdIO"
task_name = "subscriber"
command = "uv"
args = ["run", "subscriber.py"]
working_directory = "${MICLOW_CONFIG_DIR}"
view_stdout = true
view_stderr = true
subscribe_topics = ["topic0", "topic1", "topic2", "topic3", "topic4"]

[[tasks.lifecycle]]
desired_instances = 1

[[tasks]]
protocol = "MiclowStdIO"
task_name = "dynamic_subscriber"
command = "uv"
args = ["run", "dynamic_subscriber.py"]
working_directory = "${MICLOW_CONFIG_DIR}"
view_stdout = true
view_stderr = true
subscribe_topics = ["system.subscribe"]

[[tasks.lifecycle]]
desired_instances = 1

