[[tasks]]
task_name = "main"
protocol = "MiclowStdIO"
command = "uv"
args = ["run", "python3", "main.py"]
working_directory = "./src"
environment_vars = { PYTHONUNBUFFERED = "1" }
view_stdout = true
view_stderr = true

[[tasks]]
task_name = "chat"
protocol = "MiclowStdIO"
command = "uv"
args = ["run", "python3", "chat.py"]
working_directory = "./src"
environment_vars = { PYTHONUNBUFFERED = "1" }
view_stdout = true
view_stderr = true
subscribe_topics = ["system"]

[[tasks]]
task_name = "receive"
protocol = "MiclowStdIO"
command = "uv"
args = ["run", "python3", "receive.py"]
working_directory = "./src"
environment_vars = { PYTHONUNBUFFERED = "1" }
view_stdout = true
view_stderr = true
subscribe_topics = ["data"]