[[tasks]]
protocol = "MiclowStdIO"
task_name = "basic_sender"
command = "uv"
args = ["run", "sender.py"]
working_directory = "${MICLOW_CONFIG_DIR}"
view_stdout = false
view_stderr = false

  [[tasks.lifecycle]]
  desired_instances = 1

[[tasks]]
protocol = "MiclowStdIO"
task_name = "basic_receiver"
command = "uv"
args = ["run", "receiver.py"]
working_directory = "${MICLOW_CONFIG_DIR}"
view_stdout = true
view_stderr = true
subscribe_topics = ["demo.topic"]

  [[tasks.lifecycle]]
  desired_instances = 2

